spring.jpa.open-in-view=false

spring.datasource.url=jdbc:mysql://localhost:3306/timetable_engine

spring.datasource.username=root
spring.datasource.password=Root@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

timetable.max-teacher-periods-per-day=6

timetable.teacher-max-weekly-periods=30

timetable.strategy.remaining-demand-weight=100

timetable.strategy.daily-repetition-penalty=1000

timetable.strategy.consecutive-subject-penalty=500

timetable.strategy.same-period-weekly-penalty=125

timetable.strategy.previous-day-same-period-penalty=100

timetable.strategy.heavy-early-bonus=80

timetable.strategy.light-late-bonus=60

timetable.strategy.neutral-placement-bonus=20

timetable.scoring.remaining-demand-weight=100

timetable.scoring.weekly-distribution-weight=125

timetable.scoring.daily-distribution-weight=1000

timetable.scoring.consecutive-subject-penalty=500

timetable.scoring.previous-day-same-period-penalty=100

timetable.scoring.rotation-bonus=25

timetable.scoring.heavy-subject-weight=150

timetable.scoring.heavy-light-balance-bonus=30

timetable.scoring.teacher-utilization-weight=80

timetable.scoring.teacher-current-usage-penalty=20

timetable.scoring.activity-placement-weight=60

timetable.scoring.heavy-morning-weight=40

server.port=8080
